---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-pki-operator-security-configmaps
  namespace: security
  labels:
    app.kubernetes.io/name: private-pki-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: private-pki-operator-security-configmaps
subjects:
- kind: ServiceAccount
  name: private-pki-operator
  namespace: {{ .Values.namespace }}
