---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/status
  verbs:
  - patch
- apiGroups:
  - platform.adaptive-enforcement-lab.com
  resources:
  - pkirotations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.adaptive-enforcement-lab.com
  resources:
  - pkirotations/finalizers
  verbs:
  - update
- apiGroups:
  - platform.adaptive-enforcement-lab.com
  resources:
  - pkirotations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles
  verbs:
  - create
  - get
  - list
  - patch
  - watch
