---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-pki-operator
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: private-pki-operator
automountServiceAccountToken: true
