//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntermediateCARef) DeepCopyInto(out *IntermediateCARef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntermediateCARef.
func (in *IntermediateCARef) DeepCopy() *IntermediateCARef {
	if in == nil {
		return nil
	}
	out := new(IntermediateCARef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRotation) DeepCopyInto(out *PKIRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRotation.
func (in *PKIRotation) DeepCopy() *PKIRotation {
	if in == nil {
		return nil
	}
	out := new(PKIRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRotationList) DeepCopyInto(out *PKIRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PKIRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRotationList.
func (in *PKIRotationList) DeepCopy() *PKIRotationList {
	if in == nil {
		return nil
	}
	out := new(PKIRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PKIRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRotationSpec) DeepCopyInto(out *PKIRotationSpec) {
	*out = *in
	out.RootCA = in.RootCA
	out.TrustBundle = in.TrustBundle
	out.ReissuanceTimeout = in.ReissuanceTimeout
	if in.IntermediateCA != nil {
		in, out := &in.IntermediateCA, &out.IntermediateCA
		*out = new(IntermediateCARef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRotationSpec.
func (in *PKIRotationSpec) DeepCopy() *PKIRotationSpec {
	if in == nil {
		return nil
	}
	out := new(PKIRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKIRotationStatus) DeepCopyInto(out *PKIRotationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RotationStartedAt != nil {
		in, out := &in.RotationStartedAt, &out.RotationStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.DualTrustActiveAt != nil {
		in, out := &in.DualTrustActiveAt, &out.DualTrustActiveAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKIRotationStatus.
func (in *PKIRotationStatus) DeepCopy() *PKIRotationStatus {
	if in == nil {
		return nil
	}
	out := new(PKIRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootCARef) DeepCopyInto(out *RootCARef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootCARef.
func (in *RootCARef) DeepCopy() *RootCARef {
	if in == nil {
		return nil
	}
	out := new(RootCARef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StagingConfigMapRef) DeepCopyInto(out *StagingConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StagingConfigMapRef.
func (in *StagingConfigMapRef) DeepCopy() *StagingConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(StagingConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustBundleRef) DeepCopyInto(out *TrustBundleRef) {
	*out = *in
	out.StagingConfigMap = in.StagingConfigMap
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustBundleRef.
func (in *TrustBundleRef) DeepCopy() *TrustBundleRef {
	if in == nil {
		return nil
	}
	out := new(TrustBundleRef)
	in.DeepCopyInto(out)
	return out
}
